### ISSUE TITLE
您好，我有个关于三元组的问题 :-)

### ISSUE THREAD

**Issue by ZuoHaoyu** [Freeshman/LAnn#1]
很感谢您的开源软件！ 

我有个问题想请教，

对于三元组均来自于文本的抽取 我们能达到标注吗

比如 “”安迪的妻子是玛丽“” 中间的三元组为 （安迪， 妻子， 玛丽） 其中妻子这个“关系”也来自于文本，而非事先预定义的“关系”

我似乎没有在软件中达到类似的标注效果

**Comment by czqmike** [comment]
作者说了开放领域的有bug，目前只支持封闭领域的关系啊😂
也就是说**关系种类应该是固定的**，像你提到的从文本中抽取关系就不行

不过你也可以尝试回滚到原来的branch，如果不怕bug的话

**Comment by Freeshman** [comment]
实在不好意思，自从毕业后就没太关注我开源的这个项目。
开放关系的三元组标注后期数据处理和模型训练比较麻烦，所以没有往这个方向进行开发了。
